# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-05 10:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UrlList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_url', models.URLField()),
                ('shorten_url', models.URLField()),
                ('date_add', models.DateTimeField()),
                ('date_click', models.DateTimeField()),
                ('clicks', models.IntegerField()),
            ],
        ),
    ]
