# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-05 12:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urllist',
            name='clicks',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='urllist',
            name='date_click',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='urllist',
            name='shorten_url',
            field=models.URLField(null=True),
        ),
    ]
